### ISSUE TITLE
Incorrect host location on windwalker.io site

### ISSUE THREAD

**Issue by jfray** [ventoviro/windwalker#155]
http://windwalker.io/about/ has a broken link for your logo, pointing to what appears to be an incorrectly defined URL:

![screen shot 2015-01-02 at 7 31 33 pm](https://cloud.githubusercontent.com/assets/192726/5601479/0389c4b6-92b6-11e4-97df-f90003d077cc.png)

and here's the result:

![screen shot 2015-01-02 at 7 32 08 pm](https://cloud.githubusercontent.com/assets/192726/5601481/16cd4642-92b6-11e4-9f4a-7363402d6c63.png)

**Comment by jfray** [comment]
Considering that this project was announced on Hacker News today, you may want to resolve this and look for other instances of this soon?

**Comment by asika32764** [comment]
Thank you, we'll fix this soon on https://github.com/ventoviro/ventoviro.github.io
