### ISSUE TITLE
PHP 7 compatibility: Cannot use Windwalker\String\String as String because 'String' is a special class name

### ISSUE THREAD

**Issue by mul14** [ventoviro/windwalker#266]
When run `php bin/console migration migrate --seed`, I've got this message.

> PHP Fatal error:  Cannot use Windwalker\String\String as String because 'String' is a special class name in /vendor/windwalker/core/src/Core/Migration/Command/Migration/CreateCommand.php on line 14

I use WindWalker 2.1.7 with PHP 7.0.4. Is WindWalker support PHP 7?

**Comment by asika32764** [comment]
Please Use `Windwalker\String\StringHelper` instead, `String` has been deprecated.
