### ISSUE TITLE
Problem with composer install

### ISSUE THREAD

**Issue by xQuByte** [ventoviro/windwalker#317]
There's a problem after use composer install

```
Problem 1
    - The requested package phpunit/phpunit-skeleton-generator dev-windwalker-tm pl exists as phpunit/phpunit-skeleton-generator[2.0.0, 2.0.1, dev-master, 2.0.x-
dev] but these are rejected by your constraint.
```

After that i still see` Please run composer install First.`

**Comment by asika32764** [comment]
Which version did you installed?

**Comment by xQuByte** [comment]
2.*

**Comment by asika32764** [comment]
We have already removed `phpunit/phpunit-skeleton-generator` from our composer.json in current version.

Could you try again with this command to install newest version?

``` 
composer create-project windwalker/starter windwalker 2.*
```

**Comment by xQuByte** [comment]
The installation was successful. After using the composer and install the update when I get on windwalker.dev/www I see a blank page.

**Comment by asika32764** [comment]
Could you post the installation process log? 

You don't need to run composer install after composer create-project, composer will auto install all dependencies.

**Comment by xQuByte** [comment]
I'm sorry you had to wait so long.
`
[1;32;40mD:\laragon\www   [1;30;40m2016-06-09 12:59:10,58
[1;30;40mλ [0mcomposer create-project windwalker/starter windwalker 2.*
[32mInstalling windwalker/starter (2.1.9)[39m
  - Installing [32mwindwalker/starter[39m ([33m2.1.9[39m)
    Loading from cache

[32mCreated project in windwalker[39m
[32mLoading composer repositories with package information[39m
[32mUpdating dependencies (including require-dev)[39m
  - Installing [32mfilp/whoops[39m ([33m2.1.2[39m)
    Loading from cache

  - Installing [32mpsr/log[39m ([33m1.0.0[39m)
    Loading from cache

  - Installing [32mmonolog/monolog[39m ([33m1.19.0[39m)
    Loading from cache

  - Installing [32msymfony/yaml[39m ([33mv2.8.7[39m)
    Loading from cache

  - Installing [32mpsr/http-message[39m ([33m1.0[39m)
    Loading from cache

  - Installing [32mwindwalker/framework[39m ([33m2.1.9[39m)
    Loading from cache

  - Installing [32mwindwalker/core[39m ([33m2.1.9.2[39m)
    Loading from cache

  - Installing [32mfzaninotto/faker[39m ([33mv1.6.0[39m)
    Loading from cache

  - Installing [32mtwig/twig[39m ([33mv1.24.1[39m)
    Loading from cache

  - Installing [32msymfony/polyfill-mbstring[39m ([33mv1.2.0[39m)
    Loading from cache

  - Installing [32msymfony/console[39m ([33mv2.8.7[39m)
    Loading from cache

  - Installing [32msebastian/version[39m ([33m1.0.6[39m)
    Loading from cache

  - Installing [32mphpunit/php-text-template[39m ([33m1.2.1[39m)
    Loading from cache

  - Installing [32mwindwalker/phpunit-skeleton-generator[39m ([33m2.0.2[39m)
    Loading from cache

filp/whoops suggests installing symfony/var-dumper (Pretty print complex values better with var-dumper available)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
[32mWriting lock file[39m
[32mGenerating autoload files[39m
> Windwalker\Composer\StarterInstaller::rootInstall

Salt to generate secret [Windwalker-57594c2eb1ada]: 

Auto created secret key.

Do you want to use database? [Y/n]: y
y

Database driver only support mysql/postgresql now.
Database driver [mysql]: 

Database host [localhost]: 

Database name [acme]: 

Database user [root]: 

Database password: 


Table prefix [wind_]: 


Database config setting complete.

Install complete.

[1;32;40mD:\laragon\www   [1;30;40m2016-06-09 13:00:14,84
[1;30;40mλ [0m`

**Comment by asika32764** [comment]
It seems you install successfully. You can try to open your site from browser. Any other problem still exists?

**Comment by xQuByte** [comment]
At this moment when I go to http://windwalker.dev/www (local server) i see blank page.

**Comment by asika32764** [comment]
Could you try http://windwalker.dev/www/dev.php ?

**Comment by asika32764** [comment]
Where did you enabled the PHP server?

If you run server at `/{htdocs}/windwalker/www`, you must remove the `/www` folder on URL

**Comment by xQuByte** [comment]
Oh god... I'm so stupid.. 
Could not connect to PDO: SQLSTATE[HY000] [1049] Unknown database 'acme'.
I installed Windwalker so many times that I forgot about the database because every time I gave another :D 

Sorry for the problem that did not exist - its time to learn! :)

**Comment by xQuByte** [comment]
But error like this should show up without adding dev.php to url :)

**Comment by asika32764** [comment]
Because the default production environment attempt to hide all error message that can get rid of some one may see your server information.

But we can discuss about enable the error message in the default installation or not, if this is really useful when developing.

**Comment by asika32764** [comment]
Since issue resolved, close this first.

**Comment by xQuByte** [comment]
Yes, it would be very helpful.
Thank you for your help, and the response.

**Comment by asika32764** [comment]
There is a new issue confirmed relative to this issue, see https://github.com/ventoviro/windwalker-core/issues/212

**Comment by asika32764** [comment]
Fixed in https://github.com/ventoviro/windwalker-starter/commit/49d40b8c9a7b18fead5d6219e8a491a284c05eaf
