### ISSUE TITLE
DI Resolve Error

### ISSUE THREAD

**Issue by undercloud** [ventoviro/windwalker#318]
```PHP
	$container = new Windwalker\DI\Container;	
	$obj = $container->createObject('ArrayIterator');
```
throws

```Uncaught exception 'Windwalker\DI\Exception\DependencyResolutionException' with message 'Could not resolve dependency: array'```

but
```PHP
	$class = new \ReflectionClass('ArrayIterator');
	
	$params = $class->getConstructor()->getParameters();
	
	$args = array();
	foreach($params as $param){
		if($param->isDefaultValueAvailable()){
			$args[] = $param->getDefaultValue();
		}
	}
	
	$obj = $class->newInstanceArgs($args);
```
work fine

Also you can create this trick:
```PHP
// add init values
$container->createObject('ArrayIterator',['array' = []])
```

**Comment by undercloud** [comment]
// About trick ->createObject(...), laravel examle looks like
```PHP
	interface I {}

	class Y implements I {}
	
	class X {
		private $i;
		private $f;
	
		public function __construct(I $i, $f) {
			$this->i = $i;
			$this->f = $f;
		}
	}
	
	
	$container = new Illuminate\Container\Container;
	
	$container
		->when('X')
		->needs('I')
		->give('Y');
	
	$obj = $container->make('X',array('f' => true));
	
	var_dump($obj);
```

**Comment by asika32764** [comment]
Thank you for reporting this bug, I have fixed it with a9ce7bfee9bbad5d91fa44dc8cd53a7848fcd1e3

Will be release in next version.

**Comment by asika32764** [comment]
About the arguments, this package based on Joomla DI, which is a simpler DI package now.

There is some plans to enhance this package in version 3.x or 4.x. I will take a look about other frameworks' Container classes.

Thank you for your suggestion.

**Comment by asika32764** [comment]
Some similar functions implemented in dev environment, please see 
https://github.com/ventoviro/windwalker/tree/master/src/DI#creating-objects

This features will released after 3.0-beta3 or RC

**Comment by undercloud** [comment]
Hi, I working on my own DI\IoC, I have some issue with Facade,but found your solvation in Windwalker,here my question https://github.com/phpDocumentor/phpDocumentor2/issues/1790,maybe you can give me advice?Thanks!

**Comment by asika32764** [comment]
I think that what you what is `@method static ` tag

See https://github.com/ventoviro/windwalker-core/blob/master/src/Core/Cache/CoreCache.php#L19-L33

and https://phpdoc.org/docs/latest/references/phpdoc/tags/method.html

**Comment by undercloud** [comment]
Ok) Thank you!04.10.2016, 14:31, "Simon Asika" <notifications@github.com>:I think that what you what is @method static tag

See https://github.com/ventoviro/windwalker-core/blob/master/src/Core/Cache/CoreCache.php#L19-L33

and https://phpdoc.org/docs/latest/references/phpdoc/tags/method.html
