### ISSUE TITLE
IoC issue

### ISSUE THREAD

**Issue by undercloud** [ventoviro/windwalker#349]
http://windwalker.io/documentation/3.x/core/ioc-container.html
> If you want to add your own object in Ioc, edit the /src/Windwalker/Ioc.php

Cannot find source for this file :( so interesting architecture and how IDE provide autocomplete

**Comment by asika32764** [comment]
You must install `windwalker/starter` to use this class

Currently please try 2.1.x first, 3.x is not stable.

```
composer create-project windwalker/starter your_project ~2.0
```

**Comment by undercloud** [comment]
:+1: thanks
