### ISSUE TITLE
Postgresql migration error

### ISSUE THREAD

**Issue by kiyayeh** [ventoviro/windwalker#474]
1. 
echo $query;
```
CREATE TABLE IF NOT EXISTS "migration_log" (
"version" varchar(255) NOT NULL,
"start_time" timestamp NOT NULL DEFAULT '1970-01-02 00:00:01',
"end_time" timestamp NOT NULL DEFAULT '1970-01-02 00:00:01'
) ;
```

2.錯誤截圖
![1__kiyashy_mbpr___var_amwww_anna__zsh_](https://user-images.githubusercontent.com/5356980/32045890-119bda8c-ba07-11e7-9c4a-6501a46d4d9b.jpg)

**Comment by asika32764** [comment]
Fixed f2d447f82f2dbc6b42064a09b59fb28a56a91ea4

**Comment by asika32764** [comment]
把 `vendor/windwalker/framework` 刪除，直接 `git clone git@github.com:ventoviro/windwalker.git framework` 就能測試最新的版本

沒有問題我再發布新版
