### ISSUE TITLE
Wrong version in installed version after update

### ISSUE THREAD

**Issue by ribo72** [ventoviro/windwalker#514]
Hello, there is an update in Windwalker Framework and it show 4.1.16 Installed and 4.1.17 Available . When you install the update in joomla update for extensions after it show 2.1.18 Installed and 4.1.17 Available, so every time you update it show that it needs update

**Comment by asika32764** [comment]
Thank you for report this issue, it is Windwalker RAD issue https://github.com/ventoviro/windwalker-joomla-rad

We will update a new version to solve this problem.

**Comment by asika32764** [comment]
Move to https://github.com/ventoviro/windwalker-joomla-rad/issues/290
