### ISSUE TITLE
always ask to update joomla 3x

### ISSUE THREAD

**Issue by benjokoren** [ventoviro/windwalker#518]
hello,
the plugin always ask to update even after i update it and clear cache it still appear in the joomla updater section, can you fix this pls ?

Windwalker Framework | Site | Library | 2.1.18 | 4.1.17 | N/A | Update
![image](https://user-images.githubusercontent.com/22411272/44625515-30533680-a914-11e8-8993-3189c062715b.png)

**Comment by asika32764** [comment]
Please try install this version: https://github.com/ventoviro/windwalker-joomla-rad/releases/tag/2.1.18
