### ISSUE TITLE
WindWalker Ext - not updating from 2.1.18 to 4.1.17

### ISSUE THREAD

**Issue by pici65** [ventoviro/windwalker#523]
Hello
 in all joomla! sites
when I click update or receive "ok"
but nothing change
or
"Warning
Update: :Extension: Could not open "
in both cases the update is not possible.

If I download the zip from
here
https://github.com/ventoviro/windwalker
I receive
"JInstaller: :Install: Non è stato possibile trovare il file di setup XML di Joomla"

Thanks for attention or any help

**Comment by cechub** [comment]
Hi - have the same problem - here is the plug in and error response! 
 
  | Windwalker Framework | Site | Library | 2.1.18 | 4.1.17 | N/A | Update | https://raw.githubusercontent.com/ventoviro/windwalker-joomla-rad/staging/update.xml	http://windwalker.io

Warning
JFolder::create: Infinite loop detected.
Update path does not exist.
×
Message
Error updating COM_INSTALLER_TYPE_TYPE_.

**Comment by cechub** [comment]
Cant find the plug in to uninstall and tried install the plug in from your site but no change - does not want to update!

**Comment by asika32764** [comment]
Please try this version: https://github.com/ventoviro/windwalker-joomla-rad/releases/tag/2.1.18
