### ISSUE TITLE
Column prefixing?

### ISSUE THREAD

**Issue by xtremevision** [ventoviro/windwalker#687]
Hi,

Can DM do auto column prefixing so columns in a joined table would be prefixed?

Thanks,
Michael.

**Comment by asika32764** [comment]
See https://github.com/ventoviro/windwalker-datamapper#join-tables

**Comment by xtremevision** [comment]
Ok, excellent. Has this been adapted to CodeIgniter?

**Comment by asika32764** [comment]
DatabaseFactory can add pdo as source, my way is as below:

```
application/config/hooks.php
```

<?php

use Windwalker\Database\DatabaseFactory;

defined('BASEPATH') OR exit('No direct script access allowed');

/*
| -------------------------------------------------------------------------
| Hooks
| -------------------------------------------------------------------------
| This file lets you define "hooks" to extend CI without hacking the core
| files.  Please see the user guide for info:
|
|	http://codeigniter.com/user_guide/general/hooks.html
|
*/

$hook['post_controller_constructor'][] = function () {
    $ci = get_instance();

    if (!$ci) {
        return;
    }

    /** @var CI_DB_pdo_driver $db */
    $db = $ci->db;

    /** @var PDO $pdo */
    $pdo = $db->conn_id;

    // Init Windwalker Db
    DatabaseFactory::getDbo('mysql', ['resource' => $pdo]);
};
